import { afterEach, expect, it, vi } from "vitest";
import { createRenderSchedule } from "./render-schedule.js";
afterEach(() => vi.useRealTimers());
it("groups streamed updates for 33ms, flushes final output and cancels on disposal", () => {
  vi.useFakeTimers();
  const render = vi.fn();
  const schedule = createRenderSchedule(render);
  schedule.request(true);
  vi.advanceTimersByTime(16);
  schedule.request(true);
  vi.advanceTimersByTime(16);
  expect(render).not.toHaveBeenCalled();
  vi.advanceTimersByTime(1);
  expect(render).toHaveBeenCalledTimes(1);
  schedule.request(true);
  vi.advanceTimersByTime(32);
  expect(render).toHaveBeenCalledTimes(1);
  schedule.request(false);
  expect(render).toHaveBeenCalledTimes(2);
  vi.advanceTimersByTime(1);
  expect(render).toHaveBeenCalledTimes(2);
  schedule.request(true);
  vi.advanceTimersByTime(33);
  expect(render).toHaveBeenCalledTimes(3);
  schedule.request(true);
  schedule.dispose();
  vi.advanceTimersByTime(33);
  expect(render).toHaveBeenCalledTimes(3);
  expect(vi.getTimerCount()).toBe(0);
});
