import type { ParityCopy } from "../src/parity/copy.js";

/** The Spanish catalogue, as the application resolves it, for tests. */
export const PARITY_TEST_COPY: ParityCopy = Object.freeze({
  approval: Object.freeze({
    approve: "Autorizar",
    approved: "Autorizado",
    cancelled: "Cancelado",
    collapse: "v contraer",
    editAfter: "+ después",
    editAll: "todas las apariciones",
    editBefore: "- antes",
    editOne: "una aparición",
    executeWarning:
      "El comando se ejecutará con tus permisos del sistema; puede modificar archivos fuera del proyecto.",
    expand: "> mostrar todo",
    lines: (count: number) => `${String(count)} ${count === 1 ? "línea" : "líneas"}`,
    reasonPlaceholder: "Motivo opcional; Enter para confirmar",
    reject: "Rechazar",
    rejected: "Rechazado",
    rejectedWithReason: "Rechazado: {{reason}}",
    title: "Autorizar · {{name}}",
  }),
  banner: Object.freeze({
    branch: "rama",
    directory: "directorio",
    footer: "/help para los comandos · /exit para terminar",
    model: "modelo",
    repository: "repositorio",
  }),
  commands: Object.freeze({
    details: "alternar outputs compactos o detallados",
    exit: "salir de Marea",
    help: "mostrar los comandos y atajos",
    language: "cambiar el idioma de la interfaz",
    retry: "reanudar el último turno interrumpido",
  }),
  composerPlaceholder: "Escribe a Marea…",
  failure: Object.freeze({
    recoveryPending: "Hay un turno guardado pendiente de reanudación.",
    deadlineExceeded: "Se ha alcanzado el tiempo máximo de esta petición.",
    budgetExhausted: "La sesión no dispone de presupuesto suficiente para otra petición.",
    concurrencyLimited: "Hay otra petición en curso. Espera a que termine.",
    providerInterrupted: "El proveedor ha interrumpido la respuesta.",
    requestFailed: "El servidor del profesor no ha podido completar la solicitud.",
    resumeDetail: "Puedes reanudar el turno desde el último punto guardado.",
    sessionUnavailable: "La sesión ya no está disponible.",
  }),
  help: "## Comandos\n",
  hints: Object.freeze({
    approval: "Y autorizar · N rechazar · Shift+Tab revisar",
    questions: "Tab navegar · Enter continuar",
    ready: "Ctrl+O último output · PgUp/PgDn conversación · /help",
    turn: "Esc interrumpir",
  }),
  notices: Object.freeze({
    quitHint: "Pulsa Ctrl+D para salir.",
    clipboard: "Texto copiado al portapapeles",
    draftKept: "Podrás enviarlo cuando Marea termine de responder.",
    noOutputs: "Todavía no hay outputs",
    noRetry: "No hay ningún turno interrumpido para reintentar",
    noTurnOutputs: "Este turno todavía no tiene outputs",
    languageChanged: "Idioma de la interfaz: {{language}}",
    languageSaveFailed: "El nuevo idioma de la interfaz está activo, pero no se ha podido guardar.",
    outputsCompact: "Outputs compactos",
    outputsDetailed: "Outputs detallados",
    retrying: "↻ Reintentando el turno interrumpido…",
  }),
  preparing: "Preparando la sesión…",
  question: Object.freeze({
    cancelled: "Cancelado",
    next: "Siguiente",
    placeholder: "Número de opción o respuesta",
    previous: "Anterior",
    progress: "Pregunta {{index}} de {{total}}",
    required: "Esta pregunta es obligatoria.",
    send: "Enviar respuestas",
    sent: "Respuestas enviadas",
    title: "El agente necesita que decidas",
  }),
  seconds: "{{seconds}}s",
  status: Object.freeze({
    finishing: "finalizando",
    ready: "listo",
    responding: "respondiendo",
    retrying: "reintentando",
    reviewing: "revisando proyecto",
    starting: "preparando",
    thinking: "pensando",
    unrecoverable: "error no recuperable",
    waitingAnswer: "esperando respuesta",
    waitingApproval: "esperando autorización",
  }),
  title: "Marea Code",
  tool: Object.freeze({
    emptyOutput: "(sin output)",
    linesRead: (count: number) =>
      `${String(count)} ${count === 1 ? "línea" : "líneas"} leída${count === 1 ? "" : "s"}`,
    omittedMany: (count: number) =>
      `… ${String(count)} ${count === 1 ? "línea" : "líneas"} anteriores`,
    omittedOne: "… 1 línea anterior",
    output: "output",
    seeContent: "Ctrl+O para ver el contenido",
    seeOutput: "Ctrl+O para ver el output completo",
  }),
  turn: Object.freeze({
    driverFailed: "La interfaz no pudo completar el turno.",
    interrupted: "Turno interrumpido.",
    retry: "Reintentar / continuar",
    retryStarted: "Reintento iniciado",
  }),
});
