import { createHash } from "node:crypto";
import { dirname, relative, sep } from "node:path";

import type { DiscoveredCatalog, ManifestSource } from "./discovery.js";

export function renderCatalog(catalog: DiscoveredCatalog, outputFile: string): string {
  const imports = [
    ...renderImports(catalog.identityProviders, "identityProviderPlugin", outputFile),
    ...renderImports(catalog.inferenceProviders, "inferenceProviderPlugin", outputFile),
    ...renderImports(catalog.telemetryExporters, "telemetryExporterPlugin", outputFile),
    ...renderImports(catalog.dashboardModules, "dashboardModulePlugin", outputFile),
    ...renderImports(catalog.dashboardThemes, "dashboardThemePlugin", outputFile),
  ];
  const lines = [
    "// This file is generated by scripts/generate-plugin-catalog.ts. Do not edit it.",
    "import type {",
    "  DashboardModuleCatalogEntry,",
    "  DashboardThemeCatalogEntry,",
    "  IdentityProviderCatalogEntry,",
    "  InferenceProviderCatalogEntry,",
    "  TelemetryExporterCatalogEntry,",
    '} from "@marea/plugin-api";',
  ];
  if (imports.length > 0) {
    lines.push("", ...imports);
  }
  lines.push(
    "",
    ...renderRegistry(
      "identityProviderCatalog",
      "IdentityProviderCatalogEntry",
      "identityProviderPlugin",
      catalog.identityProviders,
    ),
    "",
    ...renderRegistry(
      "inferenceProviderCatalog",
      "InferenceProviderCatalogEntry",
      "inferenceProviderPlugin",
      catalog.inferenceProviders,
    ),
    "",
    ...renderRegistry(
      "telemetryExporterCatalog",
      "TelemetryExporterCatalogEntry",
      "telemetryExporterPlugin",
      catalog.telemetryExporters,
    ),
    "",
    ...renderRegistry(
      "dashboardModuleCatalog",
      "DashboardModuleCatalogEntry",
      "dashboardModulePlugin",
      catalog.dashboardModules,
    ),
    "",
    ...renderRegistry(
      "dashboardThemeCatalog",
      "DashboardThemeCatalogEntry",
      "dashboardThemePlugin",
      catalog.dashboardThemes,
    ),
    "",
    "export const dashboardCatalogRevision =",
    `  "${catalogRevision(catalog)}";`,
    "",
  );
  return lines.join("\n");
}

function renderImports<Manifest extends { readonly entrypoint: string; readonly id: string }>(
  sources: readonly ManifestSource<Manifest>[],
  importPrefix: string,
  outputFile: string,
): readonly string[] {
  return sources.map(
    (source, index) =>
      `import ${importPrefix}${String(index)} from "${moduleSpecifier(outputFile, source.entrypointFile)}";`,
  );
}

function renderRegistry<Manifest extends { readonly entrypoint: string; readonly id: string }>(
  exportName: string,
  pluginType: string,
  importPrefix: string,
  sources: readonly ManifestSource<Manifest>[],
): readonly string[] {
  if (sources.length === 0) {
    return [`export const ${exportName}: readonly ${pluginType}[] = Object.freeze([]);`];
  }
  const entries = sources.map((source, index) => {
    const manifest = JSON.stringify(source.manifest);
    return `  // prettier-ignore\n  { ...${importPrefix}${String(index)}, manifest: ${manifest} },`;
  });
  return [
    `export const ${exportName}: readonly ${pluginType}[] = Object.freeze([`,
    ...entries,
    "]);",
  ];
}

function moduleSpecifier(outputFile: string, entrypointFile: string): string {
  const relativePath = relative(dirname(outputFile), entrypointFile)
    .split(sep)
    .join("/")
    .replace(/\.ts$/, ".js");
  return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
}

/** The dashboard bundle never loads identity providers, so they do not change its revision. */
export function catalogRevision(catalog: DiscoveredCatalog): string {
  const manifests = [
    ...catalog.inferenceProviders,
    ...catalog.telemetryExporters,
    ...catalog.dashboardModules,
    ...catalog.dashboardThemes,
  ].map(({ manifest, artifactRevision }) => ({
    ...Object.fromEntries(
      Object.entries(manifest).filter(
        ([key]) => key !== "browserEntrypoint" && key !== "entrypoint",
      ),
    ),
    ...(artifactRevision ? { artifactRevision } : {}),
  }));
  return createHash("sha256").update(canonicalJson(manifests)).digest("hex");
}
type CatalogJson =
  string | number | boolean | readonly CatalogJson[] | { readonly [key: string]: CatalogJson };

function canonicalJson(value: CatalogJson): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (typeof value === "object")
    return `{${Object.entries<CatalogJson>(value)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, item]) => `${JSON.stringify(key)}:${canonicalJson(item)}`)
      .join(",")}}`;
  return JSON.stringify(value);
}
export function renderBrowserCatalog(catalog: DiscoveredCatalog, outputFile: string): string {
  const modules = catalog.dashboardModules.map((source) => {
    if (!source.browserEntrypointFile)
      throw new TypeError("Dashboard module browser entrypoint is missing.");
    return renderLoader(
      source.manifest.id,
      moduleSpecifier(outputFile, source.browserEntrypointFile),
    );
  });
  const descriptors = catalog.dashboardModules.map((source) =>
    renderLoader(source.manifest.id, moduleSpecifier(outputFile, source.entrypointFile)),
  );
  const themes = catalog.dashboardThemes.map((source) =>
    renderLoader(source.manifest.id, moduleSpecifier(outputFile, source.entrypointFile)),
  );
  return [
    "// This file is generated by scripts/generate-plugin-catalog.ts. Do not edit it.",
    "export const dashboardCatalogRevision =",
    `  "${catalogRevision(catalog)}";`,
    renderLoaders("dashboardModuleLoaders", modules),
    renderLoaders("dashboardModuleDescriptorLoaders", descriptors),
    renderLoaders("dashboardThemeLoaders", themes),
    "",
  ].join("\n");
}
function renderLoaders(name: string, entries: readonly string[]): string {
  const body = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;
  return `export const ${name} = Object.freeze(${body});`;
}

function renderLoader(id: string, path: string): string {
  const field = `  "${id}": () =>`;
  const expression = `import("${path}"),`;
  const line = `${field} ${expression}`;
  return line.length > 100 ? `${field}\n    ${expression}` : line;
}
