import { formatPlural, type Translator } from "@marea/i18n";
import type { ParityCopy } from "@marea/student-tui";

export function createParityCopy(translator: Translator): ParityCopy {
  return {
    title: "Marea Code",
    preparing: translator.t("student.tui.status.preparing"),
    composerPlaceholder: translator.t("student.tui.composer.placeholder"),
    failure: {
      recoveryPending: translator.t("student.tui.failure.recovery-pending"),
      deadlineExceeded: translator.t("student.tui.failure.deadline-exceeded"),
      budgetExhausted: translator.t("student.tui.failure.budget-exhausted"),
      concurrencyLimited: translator.t("student.tui.failure.concurrency-limited"),
      providerInterrupted: translator.t("student.tui.failure.provider-interrupted"),
      requestFailed: translator.t("errors.server.error"),
      resumeDetail: translator.t("student.tui.failure.resume-detail"),
      sessionUnavailable: translator.t("errors.run.unavailable"),
    },
    help: translator.t("student.tui.help"),
    seconds: translator.t("student.tui.status.detail"),
    approval: {
      approve: translator.t("student.tui.approval.approve"),
      approved: translator.t("student.tui.approval.approved"),
      cancelled: translator.t("student.tui.approval.cancelled"),
      collapse: translator.t("student.tui.approval.collapse"),
      editAfter: translator.t("student.tui.approval.edit-after"),
      editAll: translator.t("student.tui.approval.edit-all"),
      editBefore: translator.t("student.tui.approval.edit-before"),
      editOne: translator.t("student.tui.approval.edit-one"),
      executeWarning: translator.t("student.tui.approval.execute-warning"),
      expand: translator.t("student.tui.approval.expand"),
      lines: (count) =>
        formatPlural(translator.locale, count, {
          one: translator.t("student.tui.approval.lines.one", { count }),
          other: translator.t("student.tui.approval.lines.other", { count }),
        }),
      reasonPlaceholder: translator.t("student.tui.approval.reason-placeholder"),
      reject: translator.t("student.tui.approval.reject"),
      rejected: translator.t("student.tui.approval.rejected"),
      rejectedWithReason: translator.t("student.tui.approval.rejected-with-reason"),
      title: translator.t("student.tui.approval.title"),
    },
    banner: {
      branch: translator.t("student.tui.banner.branch"),
      directory: translator.t("student.tui.banner.directory"),
      footer: translator.t("student.tui.banner.footer"),
      model: translator.t("student.tui.banner.model"),
      repository: translator.t("student.tui.banner.repository"),
    },
    commands: {
      details: translator.t("student.tui.command.details-description"),
      exit: translator.t("student.tui.command.exit-description"),
      help: translator.t("student.tui.command.help-description"),
      language: translator.t("student.tui.command.language-description"),
      retry: translator.t("student.tui.command.retry-description"),
    },
    hints: {
      approval: translator.t("student.tui.hint.approval"),
      questions: translator.t("student.tui.hint.questions"),
      ready: translator.t("student.tui.hint.ready"),
      turn: translator.t("student.tui.hint.turn"),
    },
    notices: {
      quitHint: translator.t("student.tui.notice.quit-hint"),
      clipboard: translator.t("student.tui.notice.clipboard"),
      draftKept: translator.t("student.tui.notice.draft-kept"),
      noOutputs: translator.t("student.tui.notice.no-outputs"),
      noRetry: translator.t("student.tui.notice.no-retry"),
      noTurnOutputs: translator.t("student.tui.notice.no-turn-outputs"),
      languageChanged: translator.t("student.tui.notice.language-changed"),
      languageSaveFailed: translator.t("student.tui.notice.language-save-failed"),
      outputsCompact: translator.t("student.tui.notice.outputs-compact"),
      outputsDetailed: translator.t("student.tui.notice.outputs-detailed"),
      retrying: translator.t("student.tui.notice.retrying"),
    },
    question: {
      cancelled: translator.t("student.tui.question.cancelled"),
      next: translator.t("student.tui.question.next"),
      placeholder: translator.t("student.tui.question.placeholder"),
      previous: translator.t("student.tui.question.previous"),
      progress: translator.t("student.tui.question.progress"),
      required: translator.t("student.tui.question.required"),
      send: translator.t("student.tui.question.send"),
      sent: translator.t("student.tui.question.sent"),
      title: translator.t("student.tui.question.title"),
    },
    status: {
      finishing: translator.t("student.tui.status.finishing"),
      ready: translator.t("student.tui.status.ready"),
      responding: translator.t("student.tui.status.responding"),
      retrying: translator.t("student.tui.status.retrying"),
      reviewing: translator.t("student.tui.status.reviewing"),
      starting: translator.t("student.tui.status.starting"),
      thinking: translator.t("student.tui.status.thinking"),
      unrecoverable: translator.t("student.tui.status.unrecoverable"),
      waitingAnswer: translator.t("student.tui.status.waiting-answer"),
      waitingApproval: translator.t("student.tui.status.waiting-approval"),
    },
    tool: {
      emptyOutput: translator.t("student.tui.tool.empty-output"),
      linesRead: (count) =>
        formatPlural(translator.locale, count, {
          one: translator.t("student.tui.tool.lines-read.one", { count }),
          other: translator.t("student.tui.tool.lines-read.other", { count }),
        }),
      omittedMany: (count) =>
        formatPlural(translator.locale, count, {
          one: translator.t("student.tui.tool.omitted-many.one", { count }),
          other: translator.t("student.tui.tool.omitted-many.other", { count }),
        }),
      omittedOne: translator.t("student.tui.tool.omitted-one"),
      output: translator.t("student.tui.tool.output"),
      questionLabel: translator.t("student.tui.tool.question"),
      seeContent: translator.t("student.tui.tool.see-content"),
      seeOutput: translator.t("student.tui.tool.see-output"),
      subagentLabel: translator.t("student.tui.tool.subagent"),
    },
    turn: {
      driverFailed: translator.t("student.tui.turn.driver-failed"),
      interrupted: translator.t("student.tui.turn.interrupted"),
      retry: translator.t("student.tui.turn.retry"),
      retryStarted: translator.t("student.tui.turn.retry-started"),
    },
  };
}
