import { expect, it, vi } from "vitest";
import { SessionDrafts } from "./session-drafts.js";
import { evaluationClientFixture } from "../evaluation/evaluation.fixture.js";

it("reuses each session's draft and disposes removed entries before creating fresh ones", async () => {
  const client = evaluationClientFixture();
  const changed = vi.fn();
  const drafts = new SessionDrafts(client, { publish: vi.fn(), query: vi.fn() }, changed);
  await drafts.openReview(null);
  expect(client.history).not.toHaveBeenCalled();
  expect(drafts.review(null)).toBeUndefined();
  expect(drafts.notice(null)).toBeUndefined();
  drafts.select("run:one");
  await drafts.openReview("run:one");
  const review = drafts.review("run:one");
  const notice = drafts.notice("run:one");
  expect(review).toBeDefined();
  expect(notice).toBeDefined();
  if (review === undefined || notice === undefined) throw new Error("Missing drafts");
  const disposeReview = vi.spyOn(review, "dispose");
  const disposeNotice = vi.spyOn(notice, "dispose");
  await drafts.openReview("run:one");
  drafts.select("run:one");
  expect(drafts.review("run:one")).toBe(review);
  expect(drafts.notice("run:one")).toBe(notice);
  drafts.remove("run:one");
  expect(disposeReview).toHaveBeenCalledOnce();
  expect(disposeNotice).toHaveBeenCalledOnce();
  expect(drafts.review("run:one")).toBeUndefined();
  expect(drafts.notice("run:one")).toBeUndefined();
  drafts.remove("run:absent");
  drafts.select("run:one");
  await drafts.openReview("run:one");
  expect(drafts.review("run:one")).not.toBe(review);
  expect(drafts.notice("run:one")).not.toBe(notice);
  const currentReview = drafts.review("run:one");
  const currentNotice = drafts.notice("run:one");
  if (currentReview === undefined || currentNotice === undefined) throw new Error("Missing drafts");
  const currentReviewDispose = vi.spyOn(currentReview, "dispose");
  const currentNoticeDispose = vi.spyOn(currentNotice, "dispose");
  drafts.clear();
  expect(currentReviewDispose).toHaveBeenCalledOnce();
  expect(currentNoticeDispose).toHaveBeenCalledOnce();
  expect(drafts.review("run:one")).toBeUndefined();
  expect(drafts.notice("run:one")).toBeUndefined();
});
it("reports unsaved and uncertain drafts across every previously opened session", async () => {
  const client = evaluationClientFixture();
  const drafts = new SessionDrafts(client, { publish: vi.fn(), query: vi.fn() }, vi.fn());
  expect(drafts.hasUnsavedDrafts).toBe(false);
  drafts.select("run:one");
  const notice = drafts.notice("run:one");
  if (notice === undefined) throw new Error("missing notice");
  expect(drafts.hasUnsavedDrafts).toBe(false);
  notice.edit("draft");
  expect(drafts.hasUnsavedDrafts).toBe(true);
  notice.edit("");
  notice.state = { ...notice.state, uncertain: true };
  expect(drafts.hasUnsavedDrafts).toBe(true);
  notice.state = { ...notice.state, uncertain: false, busy: true };
  expect(drafts.hasUnsavedDrafts).toBe(true);
  notice.state = { ...notice.state, busy: false };
  await drafts.openReview("run:one");
  const review = drafts.review("run:one");
  if (review?.state.draft == null) throw new Error("missing review");
  expect(drafts.hasUnsavedDrafts).toBe(false);
  review.edit({ ...review.state.draft, teacherNote: "edited" });
  expect(drafts.hasUnsavedDrafts).toBe(true);
  review.state = { ...review.state, draft: null, evaluation: null };
  expect(drafts.hasUnsavedDrafts).toBe(false);
  review.state = { ...review.state, busy: true };
  expect(drafts.hasUnsavedDrafts).toBe(true);
  review.state = { ...review.state, busy: false, uncertain: true };
  expect(drafts.hasUnsavedDrafts).toBe(true);
  drafts.clear();
  expect(drafts.hasUnsavedDrafts).toBe(false);
});
